### ISSUE TITLE
Setting timezone => 'Europe/London' results in UTC

### ISSUE THREAD

**Issue by darkmudley** [saz/puppet-timezone#43]
Good Afternoon,
Using masterless Puppet 3.8.7
Whatever I set timezone to in the manifest, it gets set to UTC:

Here is the manifest:
[vagrant@dev01 control-repo]$ cat site/profiles/manifests/timezone.pp
class { 'timezone':
  timezone => 'Europe/London',
}

Here I set the TZ to Europe/Berlin:
[root@web-01 puppet]# rm /etc/localtime
rm: remove symbolic link ‘/etc/localtime’? y
[root@web-01 puppet]# ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

I run Puppet and it sets UTC:
[root@web-01 puppet]# puppet apply --modulepath=/etc/puppet/modules:/etc/puppet/site /etc/puppet/manifests/site.pp --debug
...
Debug: Class[Common]: The container Class[Profiles::Base] will propagate my refresh event
Debug: /Stage[main]/Timezone/File[/etc/localtime]: Removing existing link for replacement with /usr/share/zoneinfo/UTC
Notice: /Stage[main]/Timezone/File[/etc/localtime]/target: target changed '/usr/share/zoneinfo/Europe/Berlin' to '/usr/share/zoneinfo/UTC'
Debug: /Stage[main]/Timezone/File[/etc/localtime]: The container Class[Timezone] will propagate my refresh event

I have checked for a UTC setting in any other manifests and hiera - nothing there.
Any help would be welcome

Kind Regards
Mark

**Comment by darkmudley** [comment]
OS is CentOS Linux release 7.3.1611 (Core)

**Comment by spaulg** [comment]
This also happens to me - Ubuntu 16.04.

I have found that the /etc/timezone file is set to Europe/London, the dpkg-reconfigure command resets this back to Etc/UTC (I believe due to /etc/localtime containing Etc/UTC), then /etc/localtime is set to Europe/London.

I have to run puppet a second time to have both the /etc/localtime and /etc/timezone files to be both set to Europe/London correctly.

**Comment by saz** [comment]
Please give the latest release (v3.5.0) a try
