### ISSUE TITLE
FreeBSD tries to install package tzdata.

### ISSUE THREAD

**Issue by madelaney** [saz/puppet-timezone#51]
On FreeBSD 11.1, puppet version 4.10, when I include `timezone` in my puppet modules `include ::timezone`, by default the module tries to install the package `tzdata`.

```
Could not update: Execution of '/usr/local/sbin/pkg install -qy tzdata' returned 70: pkg: No packages available to install matching 'tzdata' have been found in the repositories
change from absent to latest failed: Could not update: Execution of '/usr/local/sbin/pkg install -qy tzdata' returned 70: pkg: No packages available to install matching 'tzdata' have been found in the repositories
```

**Comment by olevole** [comment]
package variables for FreeBSD is unset: https://github.com/saz/puppet-timezone/blob/v4.0.1/data/os/FreeBSD.yaml#L2

But when variables not set, the default parameters for the class are used.

It seems that the correct solution will be:
~~~
Optional[String]         $package                        = undef,
~~~

instead of: https://github.com/saz/puppet-timezone/blob/v4.0.1/manifests/init.pp#L42

Especially since some distributions reassign the package name. 

If make 
~~~
Optional[String]         $package                        = undef,
~~~

it is probably necessary to create common.yaml for OSes which is not defined in yaml backed ?

**Comment by madelaney** [comment]
I did create a hiera backend file for FreeBSD, which mimics the file [FreeBSD.yaml](https://github.com/saz/puppet-timezone/blob/v4.0.1/data/os/FreeBSD.yaml) yet to no avail. The module still tried to install the tzdata package.
